# Workflow to cache all assets from IPFS on Cloudflare edge nodes.
# This will speed up the loading of the gateway and reduce the load on the IPFS nodes.
#
# This workflow is scheduled to run 12 hours.

name: "Cache"

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/cache.yml"

jobs:
  cache:
    strategy:
      fail-fast: false
      matrix:
        run_number: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install requests tqdm
      - name: Cache (run ${{ matrix.run_number }})
        continue-on-error: true
        run: |
          python cache.py ${{ matrix.run_number }}
