name: "Update vanilla versions"

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Install dependencies
        run: |
          poetry export -o requirements.txt
          pip install -r requirements.txt
      - name: Update vanilla versions
        continue-on-error: true
        run: |
          python update_vanilla.py
      - name: Commit changes
        continue-on-error: true
        run: |
          git config --local user.email "bot@frsqr.xyz"
          git config --local user.name "Bot"
          git add .
          git commit -m "Update vanilla versions"
      - name: Push changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
